config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :products do
    delete :image_destroy, on: :member
    get :search, on: :collection
  end

  resources :cart_items do
    get :apply_coupon, on: :collection
  end

  resources :orders
  resources :comments
  resources :account, only: [:index]
  
end

app/views/shared/_custom_error_messages.erb
 <% if flash[:message] %>
    <p class="alert alert-danger"><%=flash[:message] %></p> <br>
<% end %>

app/views/shared/_error_partial.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="errors-alert">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <% object.errors.full_messages.each do |msg| %>
      <p class="alert alert-danger"><%= msg %></p>
    <% end %>

  </div>
<% end %>

app/views/shared/_flash_messages.erb
 <% if flash[:message] %>
    <p class="alert alert-success"><%=flash[:message] %></p> <br>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="header-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="top-left pull-left">
             
              
              <div class="search-box">
              
               <form action="/products/search" method="get">
                    <input name="search"  class="input-text" placeholder="Search By Products.."/>
                    <button type="submit" class="search-btn"><i class="fa fa-search"></i></button>                    
                </form>     
               
              </div>
            
          </div>
          <div class="top-right pull-right">
            <div id="top-links" class="nav pull-right">
              <ul class="list-inline">
                
                <%if user_signed_in?%>

                  <%=link_to "My Account" , account_index_path%>
                  <li><%= button_to "logout", destroy_user_session_path, method: :delete  %> </li>
                              
                <%else%>

                  <li><%= link_to "Register",  new_user_registration_path %></li>
                  <%=link_to "Login" , new_user_session_path%>

                <% end %>
              </ul>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="header-inner">
      <div class="col-sm-4 col-xs-6 header-left">
        <div class="shipping">
          <div class="shipping-img"></div>
          <div class="shipping-text">(+91) 000-1233<br>
            <span class="shipping-detail">24/7 Online Support</span></div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12 header-middle">
        <div class="header-middle-top">
          <div id="logo"> <a href="/"> <%= image_tag "/assets/logo.png",  class: "img-responsive" %></a> </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12 header-right">
        <div id="cart" class="btn-group btn-block">
          <a href="/cart_items/" class="btn btn-inverse btn-block btn-lg dropdown-toggle cart-dropdown-button "> <span id="cart-total"><span class="cart-title color-dark-brown">Shopping Cart</span><p><i class="fa fa-shopping-cart color-dark-brown" style="font-size:36px;margin-left:40px"></i></p></p></a>
          
               
        </div>
      </div>
    </div>
   
  </div>
</header>

app/views/shared/_noticeAndAlert.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/shared/_preloader.html.erb
<div class="preloader loader" style="display: block; background:#f2f2f2;"> <img src="assets/loader.gif"  alt="#"/></div>