config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :products do
    delete :image_destroy, on: :member
    get :search, on: :collection
  end

  resources :cart_items do
    get :apply_coupon, on: :collection
  end

  resources :orders
  resources :comments
  resources :account, only: [:index]
  
end

app/controllers/cart_items_controller.rb
require 'coupon.rb'

class CartItemsController < ApplicationController
	before_action :set_item, only: [:update, :destroy]
	before_action :set_price, only: [:index]

	def index
		@list=[]
		session[:cart]&.each { |item_id| @list << Item.find(item_id.to_s) }	
	end

	def create
		session[:cart] = [] if !session[:cart]
	
		if user_signed_in?
			@cart = current_user.cart
			@cart = current_user.create_cart if @cart.nil?
			@item=@cart.items.create(cart_item_params)
		else
			@item=Item.create(cart_item_params)
		end

		return if @item.errors.any?
		session[:cart].push(@item.id)
		flash.now[:message]="added to cart"
	end

	def update
		return if !@item.update(quantity: params[:quantity])
		flash.now[:message]="updated"
		set_price
	end

	def destroy
		return if !@item.destroy
		set_price
	end

	def apply_coupon
		if Coupon.all.key?(params[:coupon])
			@discountPercent = Coupon.all[params[:coupon]].to_f
			flash.now[:message]="Coupon applied, you have got discount of #{(@discountPercent * 100).to_s} percent"
		else
			@discountPercent=nil
			flash.now[:message]='Invalid coupon'
		end
	end

	private

	def set_item
		@item = Item.find(params[:id])
	end

	def cart_item_params
		params.require(:item).permit(:product_id,:price,:quantity)
	end

	def set_price
		@total = 0

		session[:cart]&.each do |item_id|
			item = Item.find(item_id.to_s)
			@total += item.price * item.quantity
		end
	end

end

app/helpers/cart_item_helper.rb
module CartItemHelper
end

app/views/cart_items/_item.erb
<!--Grid column-->

    <div  id="single_item<%=item.id%>" class="cart_item_card">
     <div id="message_div_<%=item.id%>" >  </div> 
      <div class="row">
     
          <div class="col-sm-2">
            
                <%= image_tag url_for(item.product.images[0]), :style => "height:150px;width:150px" %>
              
          </div>
            <div class="col-sm-10">
                
                  <div>
                    <h3><strong><%= item.product.name %></strong></h3>
                    <h5> Price per Item:  <%= item.price %> Rs</h5>
                  </div>
                 
                    <% availableQuantity = item.product.quantity%>

                      <%= form_tag url_for(:controller => 'cart_items', :action => 'update', :id => item.id ), remote: :true, method: :patch  do |f| %>
                      <div class="row">
                        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                        <div class="col-sm-2"> <h5> Quantity: </h5> </div>
                        <div class="col-sm-1"><button type="button"  class="btn btn-default"  onClick="minusQuantity(<%=item.id%>)" >-</button></div>
                        <div class="col-sm-1"> <input name="quantity" id="quantity_<%=item.id%>" style="width:50px" value="<%= item.quantity %>" readonly/>  </div>
                        <div class="col-sm-1"><button type="button"  class="btn btn-default"  onClick="plusQuantity(<%=availableQuantity%>,<%=item.id%>)">+</button></div>
                        <div class="col-sm-4"><p> </p></div>
                        <div class="col-sm-3"><%= button_to "Update", cart_items_path ,class: "btn btn-primary btn-sm", type: "submit"%></div>
                       
                      </div>
                      <%end%>

                        <div class="row">    
                        <div class="col-sm-9"><p> </p></div>
                         <div class="col-sm-3"><%= button_to "delete", { :controller => 'cart_items',:action => 'destroy', id: item.id}, method: :delete, remote: :true , class: "btn btn-primary btn-sm" %> </div>
                        
                     </div>
     
            </div>
      </div>
    </div>
  
    <!--Grid column-->

app/views/cart_items/apply_coupon.js.erb
<% if @discountPercent != nil%>
    $("#discount_input_box").val('<%=@discountPercent%>')
    $("#discount_span").html('<%=@discountPercent.to_f * 100%>')
    total=parseInt($("#total_price_input_box").val())
    discountVal=<%= @discountPercent %> * total
    payable = total - discountVal
    $("#payable_amount_input_box").val(parseInt(payable))
    $("#payable_amount_span").html(parseInt(payable))
    $("#message_div").html('<%= j render partial: "shared/flash_messages" %>')
<% else %>
    $("#message_div").html('<%= j render partial: "shared/custom_error_messages" %>')
<%end%>

app/views/cart_items/create.js.erb
<% if @item.errors.any? %>
    $("#message_div").html('<%= j render partial: "shared/error_partial", locals: {object: @item} %>')
<%else%>
    $("#message_div").html('<%= j render partial: "shared/flash_messages" %>')
<%end%>

app/views/cart_items/destroy.js.erb
$("#single_item<%=params[:id]%>").hide()
$("#total_price_input_box").val('<%= @total %>')
$("#total_price_span").html('<%= @total %>')
discountPercent=$("#discount_input_box").val()
discountVal=<%= @total %> * discountPercent
payable=<%= @total %> -discountVal
$("#payable_amount_input_box").val(parseInt(payable))
$("#payable_amount_span").html(parseInt(payable))

app/views/cart_items/index.erb
 
 <div class="container">
   <ul class="breadcrumb">
    <li><a>My Cart</a> </li>
    </ul>

    <% @list.each do |item| %>
        <%= render partial: "cart_items/item", locals: {item: item} %>
    <% end%>

  <%= form_tag url_for(controller: 'cart_items', action: 'apply_coupon' ), remote: :true, method: :get  do |f| %>
    <div id="message_div"> </div>
    <div class="row coupons">
      <div class="col-lg-2">
        Apply Coupon:
      </div>
      <div class="col-lg-8">
        <input type="text" class="form-control" name="coupon" placeholder="coupon / promo code" required>
      </div>
      <div class="col-lg-2">
        <button type="submit" class="btn btn-primary btn-sm"> Apply </button>
      </div>
    </div>
  <%end%>

<%= form_for :order , url:orders_path() do |f| %>

    <% @list.each do |item| %>
        <%= hidden_field_tag 'ids[]', item.id %>
    <% end%>
    <div class=" price-wrap">
    <div class="row price_show">
      <div class="col-lg-10">
        <strong > Total Price : </strong>
      </div>
      <div class="col-lg-2">
        <input type="hidden" name="total_price" id="total_price_input_box" value="<%=@total%>%">
        <span id="total_price_span"><%=@total%> </span> Rs.
      </div>

      <div class="col-lg-10">
        <strong > Discount : </strong>
      </div>
      <div class="col-lg-2">
        <input type="hidden" name="discount" id="discount_input_box" value="0">
        <span id="discount_span">0</span> %
      </div>

      <div class="col-lg-10 color_red">
        <strong > Payable Price After Discount : </strong>
      </div>
      <div class="col-lg-2 color_red">
        <input type="hidden" name="payable_amount" id="payable_amount_input_box" value="<%=@total%>">
        <span id="payable_amount_span"><%=@total%></span> Rs.
      </div>
    </div>
    </div>

    <div class="row price-wrap">
      <div class="col-lg-6 price_show">

        <div class="row">
          <div class="col-lg-4">
            Credit Card Number
          </div>
          <div class="col-lg-8">
            <input type="text" name="card_no" required>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-4">
            Security Code Number on Card:
          </div>
          <div class="col-lg-8">
            <input type="text" name="security_no" required>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6 ">
        <button type="submit" class="btn btn-primary"> Checkout </button>
      </div>
    </div>
  </div>
  <%end%>

app/views/cart_items/update.js.erb
<% if @item.errors.any? %>
    $("#message_div_<%=@item.id%>").html('<%= j render partial: "shared/error_partial", locals: {object: @item} %>')
<%else%>
    $("#message_div_<%=@item.id%>").html('<%= j render partial: "shared/flash_messages" %>')
    $("#total_price_input_box").val('<%= @total %>')
    $("#total_price_span").html('<%= @total %>')
    discountPercent=parseFloat($("#discount_input_box").val())
    discountVal=<%= @total %> * discountPercent
    payable=<%= @total %> - discountVal
    $("#payable_amount_input_box").val(parseInt(payable))
    $("#payable_amount_span").html(parseInt(payable))
<%end%>