config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :products do
    delete :image_destroy, on: :member
    get :search, on: :collection
  end

  resources :cart_items do
    get :apply_coupon, on: :collection
  end

  resources :orders
  resources :comments
  resources :account, only: [:index]
  
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, :description, :price, :quantity, presence: true
	validates :images, presence: true
	validates :price,:quantity, numericality: {only_integer: true}
	
	before_validation :add_serial_number

	belongs_to :user
	has_many :comments 
	has_many_attached :images 
	has_many :items, dependent: :delete_all 
	
	def add_serial_number
		self.serial_number = SecureRandom.hex 5
	end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except:[:show, :search]
    before_action :set_product, only: [:update, :destroy, :edit, :image_destroy]

    def index
        @products = current_user.products if user_signed_in?
    end
    
    def search
        @products = Product.search(params[:search])
    end

    def new
        @product = current_user.products.build
    end
    
    def show
        @product = Product.includes(comments: :user).find(params[:id])
    end
    
    def create
        @product = current_user.products.build(product_params)

        if @product.save
            redirect_to @product
        else
            render 'new'
        end
    end

    def update
        if params[:images].present?
            params[:images].each do |image|
                @product.images.attach(image)
            end
        end

        if @product.update(product_params)
            redirect_to @product
        else
            render 'edit'
        end

    end

    def destroy
        @product.destroy
    end

    def image_destroy
        attachment = @product.images.find(params[:image_id])
        attachment.purge
    end

    private 
    
    def product_params
        params.require(:product).permit(:name, :description, :user_id, :quantity, :price, :images => [])
    end

    def product_edit_params
        params.require(:product).permit(:name, :description, :user_id, :quantity, :price, :images => [])
    end

    def set_product
        @product = Product.find(params[:id])
    end

end

app/views/products/_product_for_account.erb
<div class="product-layout product-list col-lg-3 fixed-height" id="single_product_<%=product.id%>" >
          <div class="product-thumb">
            <div class="image product-imageblock"> <a href="products/<%=product.id%>"><%= image_tag url_for(product.images[0]), style: "height:200px;width:250px" ,title: product.name,  class: "img-responsive" %> </a>
              
            </div>
            <div class="caption product-detail">
              
             <p class="title product-price"><span class="price"> <%= product.name%>  </span></p>
             <p class=" product-price"><span class="">Price : $/<%= product.price%>  </span></p>
            </div>
            <div class="row button-group">
                <div class="col-sm-6">
                    <%= link_to "Edit", edit_product_path(product.id) ,class: "addtocart-btn"%>
                </div>
                <div class="col-sm-6">
                     <%= button_to "delete", { controller: 'products', action: 'destroy', id: product.id }, method: :delete, remote: :true , class: "addtocart-btn" %> 
                </div>
            </div>
          
           </div>
</div>

app/views/products/destroy.js.erb
$("#single_product_<%=@product.id%>").fadeOut()

app/views/products/edit.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9" id="content">
      <h1>Edit Product</h1>
      
      <%= form_for @product , method: :patch do |f| %>
      <%= render partial: "shared/error_partial", locals: {object: @product} %>
      <fieldset id="account">
          
          <div class="form-group ">   
          <div class="row">     
              <div class="col-sm-3">
                  <%= f.label :name, class: "col-sm-2 control-label" %><br />
              </div>      
              <div class="col-sm-9">
                  <%= f.text_field :name ,class:"form-control", placeholder: "Name" %>
              </div>
          </div>
          </div>
          
          <div class="form-group ">    
          <div class="row">                     
              <div class="col-sm-3">
                  <%= f.label :description, class: "col-sm-2 control-label" %><br />
              </div>  
              <div class="col-sm-9">
                  <%= f.text_area :description,class:"form-control", placeholder: "Description" %>
              </div>
          </div>
          </div>

          <div class="form-group ">
          <div class="row">                         
              <div class="col-sm-3">
                  <%= f.label :price, class: "col-sm-2 control-label" %><br />
              </div>  
              <div class="col-sm-9">
                  <%= f.text_field :price ,class:"form-control", placeholder: "Price", type: "number" %>
              </div>
          </div>
          </div>

          <div class="form-group ">
          <div class="row">                         
              <div class="col-sm-3">
                  <%= f.label :quantity, class: "col-sm-2 control-label" %><br />
              </div>  
              <div class="col-sm-9">
                  <%= f.text_field :quantity ,class:"form-control", placeholder: "Quantity", type: "number" %>
              </div>
          </div>
          </div>
    
      
          
          <div class="form-group ">   
          <div class="row">     

              <div class="col-sm-3">
                  <%= f.label :change_images, class: "col-sm-2 control-label" %><br />
              </div>      
              <div class="col-sm-9">
                  <%= f.file_field :images ,class:"form-control", multiple: :true%>
                    <% f.object.images.each do |image|%>
          <div class="col-sm-2" id="image_edit_<%=image.id%>">
            <span class="pip">
              <%= image_tag url_for(image), class:"imageThumb" %>
            <br/> <%= link_to("delete", image_destroy_product_path(@product.id, image_id: image.id), method: :delete, remote: true , class: "remove") %>
            </span>
          </div>  
        <%end%>  
              </div>
            
          </div>
          </div>
          
      </fieldset>
                
      <div class="buttons">
              <%= f.submit "Edit", :class =>"btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>


<script>
$(document).ready(function() {


  if (window.File && window.FileList && window.FileReader) {
    $("#product_images").on("change", function(e) {
      var files = e.target.files,
        filesLength = files.length;
        var newFileList = Array.from(e.target.files);
      for (var i = 0; i < filesLength; i++) {
        var f = files[i]
        var fileReader = new FileReader();
        fileReader.onload = (function(e) {
          var file = e.target;
          $("<span class=\"pip\">" +
            "<img class=\"imageThumb\" src=\"" + e.target.result + "\" title=\"" + file.name + "\"/>" +
            "<br/><span class=\"remove\">Remove image</span>" +
            "</span>").insertAfter("#product_images");
          $(".remove").click(function(){
            newFileList.splice(i+1);
            $(this).parent(".pip").remove();
          });
          
          // Old code here
          /*$("<img></img>", {
            class: "imageThumb",
            src: e.target.result,
            title: file.name + " | Click to remove"
          }).insertAfter("#files").click(function(){$(this).remove();});*/
          
        });
        fileReader.readAsDataURL(f);
      }
    });

    
  } else {
    alert("Your browser doesn't support to File API")
  }


      

});
</script>

app/views/products/image_destroy.js.erb
$("#image_edit_<%=params[:image_id]%>").hide()

app/views/products/index.erb
<div class="container">
  <ul class="breadcrumb">
    
    <li><a>My Products</a></li>
  </ul>
  <div class="row">
    <% @products.each do |p| %>
         <%= render partial: "products/product_for_account", locals: {product: p} %>
     <%end%> 

  </div>
</div>

app/views/products/new.erb
<div class="container">
  
    <div class="row">
        
        <div class="col-sm-9" id="content">
            <h1>Add a New Product</h1>
            
            <%= form_for :product , url:products_path do |f| %>
            <%= render partial: "shared/error_partial", locals: {object: @product} %>
                <fieldset id="account">
                    
                    <div class="form-group ">   
                    <div class="row">     
                        <div class="col-sm-3">
                            <%= f.label :name, class: "col-sm-2 control-label" %><br />
                        </div>      
                        <div class="col-sm-9">
                            <%= f.text_field :name ,class:"form-control", placeholder: "Name" %>
                        </div>
                    </div>
                    </div>
                   
                    <div class="form-group ">    
                    <div class="row">                     
                        <div class="col-sm-3">
                            <%= f.label :description, class: "col-sm-2 control-label" %><br />
                        </div>  
                        <div class="col-sm-9">
                            <%= f.text_area :description,class:"form-control", placeholder: "Description" %>
                        </div>
                    </div>
                    </div>

                   <div class="form-group ">
                   <div class="row">                         
                        <div class="col-sm-3">
                            <%= f.label :price, class: "col-sm-2 control-label" %><br />
                        </div>  
                        <div class="col-sm-9">
                            <%= f.text_field :price ,class:"form-control", placeholder: "Price", type: "number" %>
                        </div>
                    </div>
                    </div>

                    <div class="form-group ">
                   <div class="row">                         
                        <div class="col-sm-3">
                            <%= f.label :quantity, class: "col-sm-2 control-label" %><br />
                        </div>  
                        <div class="col-sm-9">
                            <%= f.text_field :quantity ,class:"form-control", placeholder: "Quantity", type: "number" %>
                        </div>
                    </div>
                    </div>
              

                    <div class="form-group ">   
                    <div class="row">     
                        <div class="col-sm-3">
                            <%= f.label :images, class: "col-sm-2 control-label" %><br />
                        </div>      
                        <div class="col-sm-9">
                            <%= f.file_field :images ,class:"form-control", multiple: :true%>
                        </div>
                    </div>
                    </div>

                </fieldset>
                
                   
                
                <div class="buttons">
                     
                        <%= f.submit "Add Product", :class =>"btn btn-primary" %>
                  
                </div>
            <% end %>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
  if (window.File && window.FileList && window.FileReader) {
    $("#product_images").on("change", function(e) {
      var files = e.target.files,
        filesLength = files.length;
      for (var i = 0; i < filesLength; i++) {
        var f = files[i]
        var fileReader = new FileReader();
        fileReader.onload = (function(e) {
          var file = e.target;
          $("<span class=\"pip\">" +
            "<img class=\"imageThumb\" src=\"" + e.target.result + "\" title=\"" + file.name + "\"/>" +
            "<br/><span class=\"remove\">Remove image</span>" +
            "</span>").insertAfter("#product_images");
          $(".remove").click(function(){
            $(this).parent(".pip").remove();
          });
          
          // Old code here
          /*$("<img></img>", {
            class: "imageThumb",
            src: e.target.result,
            title: file.name + " | Click to remove"
          }).insertAfter("#files").click(function(){$(this).remove();});*/
          
        });
        fileReader.readAsDataURL(f);
      }
    });
  } else {
    alert("Your browser doesn't support to File API")
  }
});
</script>

app/views/products/search.erb
<div class="container">
  <ul class="breadcrumb">
    
    <li><a>Products</a></li>
  </ul>
  <div class="row">
    <% @products.each do |p| %>
         <%= render partial: "home/product", locals: {product: p} %>
     <%end%> 

  </div>
</div>

app/views/products/show.erb
<div class="container">
 
  <div class="row">
 
    <div id="content" class="col-sm-12">
      <div class="row">
        <div class="col-sm-6">
          <div class="thumbnails">
              <div class="w3-content w3-display-container">
                <% @product.images.each do |img| %>
                  <div class="w3-display-container mySlides">             
                        <%= image_tag url_for(img), :style => "width:100%; height:500px" %>
                  </div>
                <% end %>
                  <button class="w3-button w3-display-left w3-brown background-color-dark-brown" onclick="plusDivs(-1)">&#10094;</button>
                  <button class="w3-button w3-display-right w3-brown" onclick="plusDivs(1)">&#10095;</button>

              </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div id="message_div">  </div>
          <h1 class="productpage-title color-dark-brown"><%= @product.name%></h1>
          <hr>
          <ul class="list-unstyled productinfo-details-top">
            
            <li><span class="productinfo-tax color-dark-brown">Price: $<%= @product.price%></span>  
            <hr>
            <li><span class="productinfo-tax color-dark-brown">Available Quantity:  </span> <%= @product.quantity%>
            <hr>
            <li><span class="productinfo-tax color-dark-brown">Serial Number:  </span> <%= @product.serial_number%>
          </ul>
          <hr>
           <input type="hidden" id="availableQuantity" value="<%= @product.quantity%>">

           <%= form_for :item , url:cart_items_path(), remote: :true do |f| %>

            <%= f.text_field :price, type: "hidden", value: @product.price %>
            <%= f.text_field :product_id, type: "hidden", value: @product.id  %>
          
          <div id="product">
            <%if @product.quantity != 0%>
            <div class="form-group">
        
              <div class="btn-group">
              
                <div class="row">
                 
                  <div class="col-sm-2"><button type="button" data-toggle="tooltip" class="btn btn-default wishlist" title="Add to Wish List" onClick="minusQuantity(<%=@product.id%>)" >-</button></div>
                  <div class="col-sm-3"> <%= f.text_field :quantity, id: "quantity_"+@product.id.to_s, style: "width:50px", value: "0", readonly: :true %>  </div>
                  <div class="col-sm-1"><button type="button" data-toggle="tooltip" class="btn btn-default wishlist" title="Add to Wish List" onClick="plusQuantity(<%=@product.quantity%>,<%=@product.id%>)">+</button></div>
                </div>
              </div>
              
              <div class="btn-group">
               <div class="row">
                <button type="submit" id="button-cart" data-loading-text="Loading..." class="btn btn-primary btn-lg btn-block addtocart">Add to Cart</button>
               </div>
              </div>
            </div>
            <%else%>
                <h4 class="color-dark-brown"> Out of stock </h4>
            <%end%>
          </div>
          <%end%>
        </div>
      </div>
        

<div class="row margin-top">
    <div id="content" class="col-sm-12">

            <ul class="breadcrumb">
                <li><a>Description</a></li>
            </ul>

            <div class="tab-content">
            
            <div class="tab-pane active" id="tab-description">
                <div class="cpt_product_description ">
                <div>
                    <p><%= @product.description %></p>
                </div>
                </div>
                
            </div>
            </div>

    </div>
</div>


<div class="row margin-top">

    <div id="content" class="col-sm-12">

            <ul class="breadcrumb">
                <li><a>Reviews</a></li>
            </ul>
            <div id="comments_div">
                
                <% @product.comments.each do |c| %>
                  <%= render partial: "comments/comment_body", locals: {comment: c} %>
                <%end%>
            </div>
            

    </div>
</div>


<div class="row">
    <div id="content" class="col-sm-12">
    
     <ul class="breadcrumb">
                <li><a>Write a Review</a></li>
            </ul>
    <div id="error_div"> </div>
    <% if user_signed_in? %>
        <%= form_for :comment , url:comments_path(), remote: :true, :html => {:id => "comment_form"}  do |f| %>
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              <div id="review"></div>
              
              
              <div class="form-group required">
                <div class="col-sm-12">
                  <label class="control-label" for="input-review">Your Review</label>
                  <textarea name="body" id="cmnt_body" rows="5" id="input-review" class="form-control"></textarea>
                  
                  <input type="hidden" name="product_id" id="product_id" value=<%= @product.id%>>
                </div>
              
              <div class="col-sm-4"></div>
              <div class="col-sm-4">
                  <button type="submit" id="cmnt_submin" data-loading-text="Loading..." class="btn btn-primary">Comment</button>
              </div>
        
        <%end%>

    <%else%>
      <div class="alert alert-danger" role="alert">
        you must login in order to add comment
      </div>
      

    <%end%>
    </div>


  </div>
  </div>

<script>

 

var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
    showDivs(slideIndex += n);
}

function showDivs(n) {
    var i;
    var x = document.getElementsByClassName("mySlides");
    if (n > x.length) { slideIndex = 1 }
    if (n < 1) { slideIndex = x.length }
    for (i = 0; i < x.length; i++) {
        x[i].style.display = "none";
    }
    x[slideIndex - 1].style.display = "block";
}
</script>